### ISSUE TITLE
Imporve the UI for the alert of Correct/Wrong ans

### ISSUE THREAD

**Issue by arjun-sir** [csivitu/WebDice#10]
FindCSI

**Problem:**
The alert displayed on the website looks very ugly/old-fashioned

**Solution:**
A better user interface for informing the user if his answer was correct.

**Comment by InsightCracker** [comment]
If you're using Chakra UI, there is a toast component to solve this issue.
It can also be done dynamically with JavaScript nd CSS.

Assigned it to me nd see what I have in my box🥰

**Comment by arjun-sir** [comment]
Yes I am looking for something done with CSS and JS. 
I have assigned it to you, All the best !

**Comment by InsightCracker** [comment]
I'll make a push request very soon

**Comment by InsightCracker** [comment]
I've made a pull request
