### ISSUE TITLE
Ramdonize the image of shinchan (i.e. display a different shinchan image everytime out of a pool of 5 images)

### ISSUE THREAD

**Issue by arjun-sir** [csivitu/WebDice#11]
FindCSI

**Problem:**
I dont want the website to get repetitive

**Solution:**
Find 5 images of shinchan online (with the same dimensions) and display a different one everytime the user refreshes

**Comment by then00bprogrammer** [comment]
hi, i think i can do this.. can you assign me this?

**Comment by then00bprogrammer** [comment]
hi, i think the recent PR does the work, is this good enough or do you want me to make some changes?

**Comment by arjun-sir** [comment]
Please refer to the PR comments and avoid commenting on issues
