### ISSUE TITLE
Increase number of total images to choose from after every correct ans(2,4,8,...) 

### ISSUE THREAD

**Issue by arjun-sir** [csivitu/WebDice#12]
FindCSI

**Problem:**
I dont want the website to get repetitive

**Solution:**
We can build a borderline game of finding csi with the level increasing each time someone choose the correct ans.
There will be 2 choices initially, then 4, then 8, and so on

**Comment by then00bprogrammer** [comment]
Hi, I would like to work on this issue. 
Please correct me if I'm wrong but we've to display double the number of images initially displayed, right?
If yes, then to what extent?
Please elaborate a bit more as I'm a lil bit confused about the task.

**Comment by arjun-sir** [comment]
The options to choose from get double each time you choose the correct answer (i.e. first we have 2 options to choose csi from, then 4, then, 8, then 16, ...)
and then the choices resets back once you've chosen the wrong answer (i.e.2 choices).

It should ideally be an unlimited loop but if that is an issue we can go on till a streak of 10 atleast.

**Comment by arjun-sir** [comment]
Lemme know if you want this to be assigned to you

**Comment by unknown7703** [comment]
assign me this issue
