### ISSUE TITLE
Create a README file for Find-CSI

### ISSUE THREAD

**Issue by arjun-sir** [csivitu/WebDice#31]
**Location of the Document**
Inside Find-CSI folder

**What needs to be added**
I want everyone to understand what this website is about and its "use case"

**Additional context**
Note: do not use any CSI template, I want to see some of your own work in here :)

**Comment by imran1509** [comment]
Can I take this on?

**Comment by arjun-sir** [comment]
Sure, I have assigned this to you

**Comment by imran1509** [comment]
> Sure, I have assigned this to you

Okay thanks working on it
