### ISSUE TITLE
Randomize dad image from a pool of 5 images

### ISSUE THREAD

**Issue by arjun-sir** [csivitu/WebDice#7]
DaddyLaugh

Adding a new feature to upgrade the horizon of dad images shown on our website

**Comment by SarveshN23** [comment]
Hello, please assign me to this issue.

**Comment by manojkrishnak** [comment]
[#21 ](https://github.com/csivitu/WebDice/pull/21) Randomize dad image from a pool of 5 images :::: **Please merge my Pull request**
