### ISSUE TITLE
Randomize the position of csi image and shinchan image

### ISSUE THREAD

**Issue by arjun-sir** [csivitu/WebDice#9]
FindCSI

**Problem:**
We need to make it more and more difficult for the user to find CSI

**Solution:**
CSI image should not only be on the left and should rotate everytime we refresh.

**Comment by then00bprogrammer** [comment]
alright, if I'm understanding this right we've to follow the pattern like l->r->l->r and so on.. right?

**Comment by then00bprogrammer** [comment]
assign me this is that's the task.

**Comment by arjun-sir** [comment]
Yes that is correct.

**Comment by gautam-mh** [comment]
@arjun-sir  assign me this task

**Comment by gautam-mh** [comment]
@arjun-sir kindly look into my PR

**Comment by arjun-sir** [comment]
We'll look into it.
Please avoid commenting on issues, and comment on your PSs if you have any questions
